@startuml
'https://plantuml.com/class-diagram
'!theme materia
left to right direction
package DataModel {
class Vereniging implements LidDao, TeamDao{
    -naam: String
    -leden: ArrayList<Lid>
    -teams: ArrayList<Team>
    +Vereniging(String naam)
    +getNaam(): String
    +getLeden(): ArrayList<Lid>
    -findLid(Lid lid): Lid
    +findLid(String achterNaam, String voorNaam): Lid
    +addLid(Lid lid): boolean
    +removeLid(Lid lid): boolean
    +updateLid(Lid lid): boolean
    +findTeam(String naam): Team
    +addTeam(Team team): boolean
    +removeTeam(Team team): boolean
    +updateTeam(Team team): boolean
    +aantalLeden(): Integer
}

class Lid {
    -achterNaam: String
    -voorNaam: String
    -tussenVoegsel: String
    -adres: Adres
    -telefoonNummer: String
    -email: String
    -geboorteJaar: Integer
    -geslacht: eGeslacht
    -team: Team
    +Lid(alle attributen - team)
    +getSamenGesteldeNaam(): String
    +getAchterNaam(): String
    +getVoorNaam(): String
    +gettussenVoegsel(): String
    +getAdres(): Adres
    +getTelefoonnummer(): String
    +getEmail(): String
    +getGeboorteJaar(): Integer
    +getGeslacht(): eGeslacht
    +getTeam(): Team
    +setTeam(team): boolean
    +setAchternaam(String): void
    +setvoorNaam(String): void
    +setTussenVoegsel(String): void
    +setAdres(Adres): void
    +setTelefoonNummer(String): void
    +setEmail(String): void
    +setGeslacht(eGeslacht): void
    +setGeboorteJaar(Interger): void
}

interface LidDao {
        getLeden(): List<Lid>
        findLid(String achternaam, String voornaam): Lid
        addLid(Lid lid): boolean
        removeLid(Lid lid): boolean
        updateLid(Lid lid): boolean
        aantalLeden(): Integer
}

class Team {
    -naam: String
    -klasse: eKlasse
    -geslacht: eGeslacht
    +Team(naam, klasse, geslacht)
    +getNaam(): String
    +getKlasse(): eKlasse
    +getGeslacht(): eGeslacht
}

interface TeamDao {
    getTeams(): List<Team>
    findTeam(String naam): Team
    addTeam(Team team): boolean
    removeTeam(Team team): boolean
    updateTeam(Team team): boolean
}

package enum {
    enum eGeslacht {
        MAN
        VROUW
        MIX
        +toString(): String
    }


    enum eKlasse {
          JUNIOR
        SENIOR
        PROMOTIE
        EREDIVISIE
        +toString(): String
    }

}
}

Team <|- eKlasse
Team <|-- eGeslacht
Lid <|- eGeslacht
Lid  *-- Team
LidDao --+ Lid
TeamDao --+ Team

@enduml